{
 "title": "Patroni",
 "tags": [
  "Patroni",
  "Postgres",
  "Percona"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "replica",
    "label": "Replicas",
    "query": "query_result(patroni_replica == 1)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(patroni_version, service_name)"
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values(patroni_version, node_name)"
   },
   {
    "name": "leader",
    "label": "leader",
    "query": "query_result(patroni_master == 1)"
   },
   { "name": "interval", "label": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Leader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Name",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "content": "$leader" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_master{service_name=~\"$leader\", scope=\"postgres\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - patroni_postmaster_start_time{service_name=~\"$leader\"}"
    }
   ]
  },
  {
   "title": "Is Cluster lock?",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "patroni_cluster_unlocked{service_name=~\"$leader\"}",
     "legendFormat": "Locked"
    }
   ]
  },
  {
   "title": "Is Paused?",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_paused{service_name=~\"$leader\"}",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "Is postgres up?",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "patroni_postgres_running{service_name=~\"$leader\", scope=\"postgres\"}",
     "legendFormat": "status"
    }
   ]
  },
  { "title": "Replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "replica" },
  {
   "title": "Service Name",
   "type": "text",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 10 },
   "options": { "content": "$replica" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_master{service_name=~\"$replica\", scope=\"postgres\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - patroni_postmaster_start_time{service_name=~\"$replica\"}"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_location{service_name=~\"$leader\"} - on (scope) patroni_xlog_replayed_location{service_name=\"$replica\"}",
     "legendFormat": "Lag "
    },
    {
     "expr": "patroni_xlog_replayed_location{service_name=\"$replica\"} - on (scope) patroni_xlog_received_location{service_name=\"$replica\"}",
     "legendFormat": "Replay to Received"
    }
   ]
  },
  {
   "title": "Is Paused?",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_paused{service_name=~\"$replica\"}",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "Is postgres up?",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "patroni_postgres_running{service_name=~\"$replica\", scope=\"postgres\"}",
     "legendFormat": "status"
    }
   ]
  }
 ]
}